### ISSUE TITLE
Science cannot be transmitted through relays

### ISSUE THREAD

**Issue by rockfactory** [Kerbalight/CommNext#6]
> Hmmmm... I wonder if there is another, separate issue from the occlusion issues having to do with science being able to connect.  I seem to remember hearing about a bug in vanilla that sometimes you could use probe control via a relay, but couldn't upload science via relays.  It never caused me grief before because I would always have a big enough antenna with the Communotron 88-88 to call home directly to KSC.  However, now with this mod we're forced to use relays because of the nerfed KSC and occlusion.  Does anyone know if this bug is still a thing in vanilla?  If so, it's a show stopper for this mod (unless we can some how fix it

> Hmmmm... I think the problem has been fixed in vanilla but it is a problem with the mod, and I don't think it is due to the occlusion bug.  I've only had the occlusion bug when close to a moon such as Laythe in the Jool system, but not when far out where my higher powered relays are.  However, even after teleporting my vessel right next to one of the relays I can't upload my science.   Here's my mk2 vessel which has a Com-88-88 on board but it isn't open.  It also has integrated transmitters in the Pod and a probe core, so it obviously should be able to reach the relay right next to it.

> You can see the relay is connected via map view, and both vessels look like they are connected with a green icon below the compas

![Image](https://github.com/Kerbalight/CommNext/assets/112330494/cc9d104f-9751-414c-86af-14311cada3cf)

![Image](https://github.com/Kerbalight/CommNext/assets/112330494/837e743f-14fa-4fe2-aefd-fe5b27cc4a3c)

![Image](https://github.com/Kerbalight/CommNext/assets/112330494/c85dbaac-a162-4a6a-bacd-ddb2fcbb917f)

> Removing the mod allows uploading science without using the Com-88-88:

> So... with vanilla, uploading science works through relays.  With CommNext currently, it doesn't appear so.  And I think this is probably separate from the occlusion issues, because it happened while right next to a relay that wasn't experiencing this issue.  Save game below

**Comment by rockfactory** [comment]
This should now be fixed in v0.5.1

**Comment by McGamezZPlayer** [comment]
![Image](https://github.com/Kerbalight/CommNext/assets/25538024/4fc56168-3a19-4bc4-9058-81f43fc88830)

I believe the bug is back. I have a probe on the mun which is connected to a relay in orbit of the mun and that is connected to a relay in a keo.
